version: '3.9'

services:
  mysql_server:
    image: mysql:8.0  # Use MySQL version 8
    # <> Expose To Public (Host machine)         <>
    ports:
      - "3306:3306"
    # <> Expose Internally (Not to Host machine) <>
    #expose:
    # - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_PASSWORD
      - MYSQL_DATABASE=TEST
    volumes:
      - ./perm/mysql-data:/var/lib/mysql
    networks:
      - back-end

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - express_app
    networks:
      - front-end
      - back-end
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html:ro
    # TODO: Add Binding to "/public" folder


  express_app:
    build: 
      context: ./
    ports:
      - "3000:3000"
    # environment:
    depends_on:
      - mysql_server
    networks:
      - back-end
    volumes:
      - ./prisma:/app/prisma
      - ./public:/app/public
      - ./facturation/generated:/app/facturation/generated
      - ./utils/logging/logs:/app/utils/logging/logs
    env_file:
      - ./.env



networks:  # Define networks for internal and external communication
  front-end:  # External network for client traffic
  back-end:  # Internal network for communication between services

volumes:  # Define persistent volumes
  mysql-data:  # Persistent storage for MySQL data
